export const MFK_ADMIN_AUTHORITY=Object.freeze({
  product:'MFK_ADMIN',
  role:'CONTROL_PLANE',
  currentSystem:'MFK',
  domainWiring:'ADMIN_TO_SMT_CONFIG_SYNC',
  configPublishEnabled:true,
  configReadbackEnabled:true,
  liveMutationEnabled:false,
  liveReadEnabled:true,
  transactionExecutionAuthority:false,
  physicalPrintExecutionAuthority:false,
  authorityFlow:[
    'OWNER_DECISION',
    'ADMIN_EDIT',
    'SAVE_VALIDATE',
    'ACTIVE_REVISION',
    'AUTO_CANONICAL_PUBLISH',
    'SMT_AUTO_LKG_APPLY',
    'SMT_EXECUTION',
  ] as const,
} as const);
