export const MFK_OWNER_AUTHORITY=Object.freeze({
  product:'MFK_OWNER',
  role:'OBSERVATION_ALERTING_REVIEW_BOUNDED_DECISION',
  currentSystem:'MFK',
  mode:'CANONICAL_READ_CONNECTION',
  domainWiring:'CANONICAL_READ_PARTIAL',
  liveNetworkReadEnabled:true,
  liveNetworkWriteEnabled:false,
  liveRemoteMutationEnabled:false,
  formalOrderAuthority:false,
  checkoutAuthority:false,
  paymentAuthority:false,
  pricingAuthority:false,
  storeKernelWriteAuthority:false,
  displayNumberAuthority:false,
  physicalPrintAuthority:false,
  cashDrawerAuthority:false,
  cloudAuthority:false,
  providerCommandAuthority:false,
  settlementRewriteAuthority:false,
  adminConfigAuthoring:false,
  allowedState:'LOCAL_SESSION_PLUS_AUTHENTICATED_CANONICAL_READ',
} as const);
