export const OWNER_UI_STAGE03_ORDER_OVERSIGHT_MAPPING={
  screenId:'OA-ORD-001',
  route:'/orders',
  mode:'READ_OVERSIGHT_FIRST',
  source:'OwnerReadModelSnapshot.orders',
  canonicalFulfillmentState:{
    ownerField:'fulfillmentLabel',
    sourceOwner:'Store Kernel / Local Runtime canonical StoredOrder',
    upstreamSeam:'v2local StoredOrder.fulfillmentLabel -> v2local projection-outbox fulfillmentLabel -> Owner order projection',
    canonicalValues:['待處理','進行中','可取餐','已完成','已取消'],
    presentationMap:{
      待處理:'未完成',
      進行中:'未完成',
      可取餐:'可取餐',
      已完成:'已取餐',
      已取消:'已取消',
    },
    missingDisplay:'未有交收狀態讀回',
    forbiddenInference:[
      'DO_NOT_USE_FULFILLMENT_MODE_AS_STATE',
      'DO_NOT_INFER_READY_OR_PICKED_UP_FROM_LIFECYCLE',
    ],
  },
  searchFields:[
    'displayCode',
    'customerName',
    'customerPhone',
    'externalRef',
  ],
  filters:[
    'businessDate',
    'source',
    'activeCompleted',
    'paymentState',
    'fulfillmentState',
  ],
  scopes:{
    default:'DEFAULT',
    activeFromToday:'ACTIVE',
    dineInOpenFromToday:'DINE_IN_OPEN',
    resetOnScopedEntry:{
      query:'',
      businessDate:'ALL',
      source:'ALL',
      segment:'ACTIVE',
      paymentState:'ALL',
      fulfillmentState:'ALL',
    },
    scopedHistoryPolicy:'HISTORY_HIDDEN_WHILE_SCOPED',
    viewAllPolicy:'RESET_SCOPE_AND_FILTERS_TO_DEFAULT',
  },
  cardFields:[
    'displayCode',
    'source',
    'workflowStatusLabel',
    'elapsedLabel',
    'promisedTimeLabel',
    'currentEffectiveAmountLabel',
    'currentTenderLabel',
    'canonicalFulfillmentState',
    'exceptionBadges',
  ],
  detailSections:[
    'IDENTITY',
    'ITEMS_OPTIONS_MODIFIERS_REMARK',
    'MONEY',
    'FULFILLMENT',
    'EXTERNAL',
    'SIDE_EFFECTS',
    'TIMELINE_AUDIT',
  ],
  prohibitedMutations:[
    'CREATE_ORDER',
    'EDIT_ORDER',
    'CANCEL_ORDER',
    'REFUND',
    'TENDER_CORRECTION',
  ],
  normalUiHidden:[
    'orderId',
    'rawEngineeringFailure',
    'rawTimeline',
    'rawPrintPayload',
  ],
} as const;

export const OWNER_UI_STAGE03_AUTHORITY_RULES=[
  'Order Oversight consumes canonical read projection only.',
  'Fulfillment state comes only from canonical fulfillmentLabel projection.',
  'Fulfillment mode remains service mode only and is never used as fulfillment state.',
  'No lifecycle-to-ready/picked-up inference is allowed.',
  'No order mutation command is exposed in Stage03.',
  'Raw UUID and engineering payloads stay outside normal UI.',
  'No second Order / Pricing / Payment / Print / Auth / Sync authority is created.',
] as const;
