export const OWNER_UI_STAGE01_DATA_MAPPING={
  screenId:'OA-TOD-001',
  route:'/today',
  source:'OwnerReadModelSnapshot',
  header:{
    storeName:'store.storeName',
    businessDay:'store.businessDate',
    operatingStatus:'store.operatingStatus',
    freshness:'store.freshness',
    observedAt:'store.observedAt',
  },
  kpi:'today',
  liveOrders:{
    source:'liveOrders',
    ctaScope:'ACTIVE',
    requiredItemFields:[
      'displayCode',
      'source',
      'amountLabel',
      'fulfillmentLabel',
      'elapsedLabel',
      'promisedTimeLabel',
      'exceptionBadge',
    ],
  },
  dineIn:{
    source:'dineIn',
    ctaScope:'DINE_IN_OPEN',
    requiredCheckFields:[
      'currentOrderTotalLabel',
      'confirmedPaidLabel',
      'outstandingLabel',
      'paymentState',
    ],
    effectiveSalesBoundary:'includedInEffectiveSales=false',
  },
  actionSummary:{
    source:'actions',
    fields:['openCount','topSeverity','oldestUnresolved'],
    note:'Only actionable Owner Action Queue items; never SMT Pending Order Queue.',
  },
  healthSummary:{
    source:'readiness.kind',
    requiredKinds:['INTERNET','KEETA','OWN_PLATFORM','SMT','PRINTER'],
    responsibility:{
      INTERNET:'devices',
      KEETA:'channels',
      OWN_PLATFORM:'channels',
      SMT:'devices',
      PRINTER:'devices',
    },
    note:'Health is not Availability; missing canonical readback stays UNAVAILABLE / UNKNOWN.',
  },
  staffSummary:{
    source:'today',
    fields:['staffNow','scheduledStaffCount','onBreakStaffCount','abnormalStaffCount'],
  },
  insight:{
    source:'insight',
    fields:['topProductLabel','currentHourTrendLabel'],
    missing:'UNAVAILABLE',
  },
  globalStates:[
    'LOADING',
    'EMPTY',
    'FRESH',
    'STALE',
    'PARTIAL',
    'OFFLINE_READONLY',
    'PERMISSION_DENIED',
    'ERROR',
    'UNKNOWN',
  ],
} as const;

export const OWNER_UI_STAGE01_AUTHORITY_RULES=[
  'Owner App is read/oversight first.',
  'Store operating status must come from canonical store projection, never connection state.',
  'Open Checks are not silently counted as Current Effective Sales.',
  'Pending / Draft / Pre-admission are not formal Sales or formal Order Count.',
  'Health is separate from Availability and provider truth must not be inferred.',
  'OFFLINE_READONLY disables remote mutation.',
  'ERROR uses human-safe UI copy; raw engineering detail belongs only in Diagnostics / log.',
  'UNKNOWN remains separate from ERROR.',
  'No direct network or second Order / Pricing / Payment / Print / Auth / Sync authority belongs in Stage01.',
] as const;
